-- AlterTable: Add multi-currency and management fields to plans
ALTER TABLE "plans" ADD COLUMN IF NOT EXISTS "priceNGN" DOUBLE PRECISION;
ALTER TABLE "plans" ADD COLUMN IF NOT EXISTS "priceGBP" DOUBLE PRECISION;
ALTER TABLE "plans" ADD COLUMN IF NOT EXISTS "yearlyMonthlyPrice" DOUBLE PRECISION;
ALTER TABLE "plans" ADD COLUMN IF NOT EXISTS "yearlyMonthlyPriceNGN" DOUBLE PRECISION;
ALTER TABLE "plans" ADD COLUMN IF NOT EXISTS "yearlyMonthlyPriceGBP" DOUBLE PRECISION;
ALTER TABLE "plans" ADD COLUMN IF NOT EXISTS "trialDays" INTEGER NOT NULL DEFAULT 7;
ALTER TABLE "plans" ADD COLUMN IF NOT EXISTS "sortOrder" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "plans" ADD COLUMN IF NOT EXISTS "isActive" BOOLEAN NOT NULL DEFAULT true;
