-- AlterTable
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "isBlocked" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "blockedAt" TIMESTAMP(3);
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "blockedReason" TEXT;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "blockedBy" TEXT;
